language: python
python:
- '3.6'
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  # required for the pip only-binary flag
  - pip install --upgrade pip setuptools wheel
  # install pandas
  - pip install --only-binary=pandas pandas
install:
  - pip install .
script: pytest --cov=data-pipeline
after_success:
  - codecov
